language:
    - node_js

node_js:
    - node

cache: npm

script:
    - echo 'Starting build.'
    - echo 'Installing Dependencies.'
    - npm ci
    - echo 'Running unit tests.'
    - npm run test:coverage

after_script:
    - npm run codecov

notifications:
    email: false
